In [13]:
import numpy as np

In [17]:
alpha_in = np.array([0.333, 0.333, 0.333])

In [18]:
node_id = [0,1,2]

reduction = 0.5

In [19]:
a_1 = [alpha_init[0]*reduction, alpha_init[1], alpha_init[2]]
a_2 = [alpha_init[0], alpha_init[1]*reduction, alpha_init[2]]
a_3 = [alpha_init[0], alpha_init[1], alpha_init[2]*reduction]
print(a_1)
print(a_2)
print(a_3)
print(a_1/sum(a_1))

[0.1665, 0.333, 0.333]
[0.333, 0.1665, 0.333]
[0.333, 0.333, 0.1665]
[0.2 0.4 0.4]


In [20]:
def node_split(alpha_init, reduction):
    
    a_1 = [alpha_init[0]*reduction, alpha_init[1], alpha_init[2]]
    a_2 = [alpha_init[0], alpha_init[1]*reduction, alpha_init[2]]
    a_3 = [alpha_init[0], alpha_init[1], alpha_init[2]*reduction]
    
    alpha_1 = a_1/sum(a_1)
    alpha_2 = a_2/sum(a_1)
    alpha_3 = a_3/sum(a_1)
    
    return alpha_1, alpha_2, alpha_3

In [21]:
alpha_1, alpha_2, alpha_3 = node_split(alpha_init, reduction)
print(alpha_1)
print(alpha_2)
print(alpha_3)

[0.2 0.4 0.4]
[0.4 0.2 0.4]
[0.4 0.4 0.2]


In [ ]:
Train_MV_shuffle = {}
Train_WAV_shuffle = {}


keys = np.arange(len(Train_MV))
np.random.shuffle(keys)

i = 0

for key in keys:

    Train_MV_shuffle[i] = Train_MV[key] 
    Train_WAV_shuffle[i] = Train_WAV[key]
    
    i = i + 1

In [22]:
def shuffle_list(input_list):
    
    shuffled_list = {}
    
    keys = np.arange(len(input_list))
    np.random.shuffle(keys)    
    
    i = 0

    for key in keys:

        shuffled_list[i] = input_list[key] 

        i = i + 1
    return shuffled_list

In [ ]:

len_1 = np.zeros([len(Train_MV_1),1], dtype=int)
len_2 = np.zeros([len(Train_MV_2),1], dtype=int)
len_3 = np.zeros([len(Train_MV_3),1], dtype=int)

for i in range(len(Train_MV_1)):
    
    len_1[i] = Train_MV_1[i].shape[0]

#print(Train_MV_1[1].shape[0])